server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml   

clients:
  - url: ${LOKI_URL:-http://loki:3100/loki/api/v1/push}

scrape_configs:
  - job_name: validation
    static_configs:
      - targets:
          - localhost
        labels:
          job: validation
          __path__: /var/lib/reports/stream.ndjson

    pipeline_stages:
      - json:
          expressions:
            type: type
            ts: ts
            run_id: run_id
            path: path
            valid: valid
            registry: registry
            service: service
            error_count: error_count
            rule_ids: rule_ids
            keywords: keywords

      - regex:
          source: path
          expression: '.*[/\\\\](?P<file_name>[^/\\\\]+)$'

      - template:
          source: sanitized_filename
          template: '{{ .file_name | lower | replace " " "_" | replace "." "_" | replace "/" "_" | replace "\\\\" "_" | replace "-" "_" }}'

      - timestamp:
          source: ts
          format: RFC3339
          action_on_failure: skip

      - labels:
          job: validation
          type:
          run_id:
          valid:
          registry:
          service:
          path:                
          filename: sanitized_filename
